### PR TITLE
Default mapStateToProps and mapDispatchToProps should not add any add…

### LINKED ISSUE #8: Passing null or undefined for mapStateToProps does the wrong behavior
From react-redux `connect`:
https://github.com/reactjs/react-redux/blob/master/docs/api.md#arguments

> If you don't want to subscribe to store updates, pass null or undefined in place of mapStateToProps.

I would expect that we could do the same for `connectWithInputs` and I would not receive any additional props to the component.

### PR DESCRIPTION
**Pull request by stonebk**
…itional props.

Fixes #8

### CODE REVIEW

**Comment by stonebk** [comment]
This is likely to break people who are using implied props, but this is definitely the correct behavior.

File: src/util/connectWithInputs.js [hunk 1]
```diff
@@ -26,33 +26,34 @@ function applyMapDispatchToProps(mapDispatchToProps, dispatch, ownProps) {
  */
 export default (
     inputConfig,
-    mapReduxInputsToProps = reduxInputs => ({ reduxInputs }),
+    mapReduxInputsToProps,
     connect = _connect
 ) => {
+    const mapReduxInputsFn = mapReduxInputsToProps || (reduxInputs => ({ reduxInputs }));
```
Comment (stonebk) [inline src/util/connectWithInputs.js]: This will work when `null` is passed now.

**Comment by jakepusateri** [comment]
LGTM
